languages = {
	check = "simp_chinese"
}

filter = {
	show_vanilla = no
	show_loaded_mods = no
	trigger = {
		always = yes
	}
}

scope_override = {
	artifact_low_rarity_trigger = ALL
	artifact_medium_rarity_trigger = ALL
	artifact_high_rarity_trigger = ALL
	artifact_region_trigger = ALL
}

output_style = {
	enable = no
}
